
# this is for getting a look at the structure of bandit data bc R > matlab --------
devtools::install_github("matsukik/mrsat")
library(mrsat)

library(tidyverse)
library(rprime)
library(wrapr)

library(reshape2)

basedir <- "~/Desktop/"
datadir <- paste0(basedir, "bandit_scripts/Bandit_withrest")


stims_fun <- function(wm_path, all) {
  # browser()
  
  # Read in a text file generated by Eprime
  wm_lines <- rprime::read_eprime(wm_path)
  # Convert lines from an Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(wm_frames)
  
  # Select the columns we want for a tibble called "dat".
  #dat <- experiment_df %>% select(qc(topstim, leftstim,rightstim)) #%>% mutate(id = unique(.$Subject))
 if(!all){
   dat <- experiment_df %>%
     select(qc(Arew, Brew, Crew,
               topstim, leftstim,rightstim, reinforced1,
               reinforced2, reinforced3))#, showstim.RESP, showstim.ACC)) #%>% mutate(id = unique(.$Subject))
 } else{dat <- experiment_df}
   
  # 
  # Only put the actual trials in "dat".
  dat <- dat[2:301, ]
  dat$topstim <- gsub(".bmp", "",dat$topstim, fixed = TRUE)
  dat$leftstim <- gsub(".bmp", "",dat$leftstim, fixed = TRUE)
  dat$rightstim <- gsub(".bmp", "",dat$rightstim, fixed = TRUE)
  dat
}

datadir <- "/Users/nth7/Desktop/bandit_sandbox/Bandit Data"
datadir <- "/Users/nth7/Downloads/Bandit Data 3"


setwd(datadir)
dirs <- list.dirs(datadir)[-1]
for(sub in list.files()[1:95]){
  #sub <- list.dirs("~/Desktop/bandit_scripts/Bandit_withrest")[2]
  print(sub)
  txt.file <- paste0(sub, "/",list.files(sub)[2])
  txt.path <-paste0(getwd(), "/", txt.file)
  temp <- stims_fun(txt.path, all = TRUE)
  rownames(temp) <- 1:nrow(temp)
  
  write.csv(temp, file = paste0(sub, "/stims_",sub,".csv"), row.names = FALSE, quote = FALSE)
}


# hacky plot of learning curves -------------------------------------------

with_rest <- read.delim("/Users/nth7/Desktop/bandit_scripts/subjs_with_rest.txt",header = FALSE)


pdf(file = "~/Desktop/bandit_scripts/learning_curves_reinforcement_with_rest_to_fit.pdf", width = 11, height = 8 )


xx <- read.csv("~/Desktop/bandit_scripts/Bandit_withrest/10/stims_10.csv")
####get p(reward) by averaging over trial blocks of 10
stepsize = 20
y <- seq(1,300,stepsize)

z <- list()
for(i in 1:length(y)){
  if(i == length(y)){
    (trials <- y[i]:300)
  } else{(trials <- y[i]:(y[i+1]-1))}
  these_trials <- xx[trials,]
  
  these_trials$A_avg <- sum(these_trials$Arew)/stepsize
  these_trials$B_avg <- sum(these_trials$Brew)/stepsize
  these_trials$C_avg <- sum(these_trials$Crew)/stepsize
  these_trials$bin <- y[i]
  these_trials$trial <- trials
  
  z[[i]] <- these_trials
  
}
# library("smoother")
# 
# these_trials$A_avg <- smth(these_trials$Arew)

z <- do.call(rbind,z)
z <- dplyr::select(z, -c(topstim, leftstim, rightstim, reinforced1, reinforced2,reinforced3, Arew, Brew,Crew,bin))
zz <- melt(data = z, id.vars = "trial", measure.vars = c("A_avg", "B_avg", "C_avg"))

save(zz, file = "/mnt/ics/Michael/bpd_rest/behavior/bandit_contingency.RData")

# reinforcement_schedule <- ggplot(zz, aes(x = trial, y = value, color = variable)) + geom_line() +geom_point()+ geom_smooth() +scale_y_continuous(limits = c(0,1))+ ggtitle("Reinforcement Contingency (roughly)") + labs(y = "reward probability")
# plot(reinforcement_schedule)



# subject behavior, for overall and individuals ---------------------------


subs_withrest <- list.files()[which(tolower(list.files()) %in% tolower(with_rest$V1) & !tolower(list.files()) %in% "071_eh")     ] 

zzz <- list()
sub_plots <- list()
for(sub in subs_withrest){
  x <- read.csv(paste0(sub, "/stims_",sub,".csv")) %>% mutate(subject = sub) %>% select(subject, Eprime.FrameNumber, showstim.RESP)
  colnames(x) <- c("subject", "trial", "chosen_stim")
  x$trial <- 1:nrow(x)
  x <- cbind(x,xx)
  
  ###this is to overwrite the bandit subject choices script
  sub_num <- as.numeric(sub("_..","", sub))
  x$chosen_stim <- ifelse(x$chosen_stim == 4, as.character(x$leftstim), ifelse(x$chosen_stim == 5, as.character(x$topstim), as.character(x$rightstim))) 
  mat_choices <- ifelse(x$chosen_stim == "A", 1, ifelse(x$chosen_stim == "B", 2, 3)) 
  write_lines(mat_choices, path = paste0("~/Desktop/bandit_scripts/Bandit_withrest/", sub_num, "/choices.txt"))
  
  
  # x <- x %>% left_join(xx,)
  x$outcome <- 0
  x$outcome <- ifelse(x$chosen_stim == "A" & x$Arew == 1, 1, ifelse(x$chosen_stim == "B" & x$Brew == 1, 1, ifelse(x$chosen_stim == "C" & x$Crew == 1, 1,0))) 
  
  write_lines(x$outcome, path = paste0("~/Desktop/bandit_scripts/Bandit_withrest/", sub_num, "/outcomes.txt"))
  # %>% dplyr::select(subject, trial, chosen_stim)
  

  ####debugging
  # b.chosen <- read.delim('~/Desktop/018_b_chosen_RESP.txt', header = FALSE)
  # x$chosen_stim  <- ifelse(b.chosen$V1 == 4, as.character(x$leftstim), ifelse(b.chosen$V1 == 5, as.character(x$topstim), as.character(x$rightstim))) 
  
  y <- seq(1,300,stepsize)
  
  z <- list()
  for(i in 1:length(y)){
    if(i == length(y)){
      (trials <- y[i]:300)
    } else{(trials <- y[i]:(y[i+1]-1))}
    these_trials <- x[trials,]
    
    these_trials$p_A <- length(which(these_trials$chosen_stim == "A"))/stepsize
    these_trials$p_B <- length(which(these_trials$chosen_stim == "B"))/stepsize
    these_trials$p_C <- length(which(these_trials$chosen_stim == "C"))/stepsize
    these_trials$bin <- y[i]
    these_trials$trial <- trials
    
    z[[i]] <- these_trials
    
  }
  zz <- do.call(rbind, z)
  yz <- dplyr::select(zz, -c(topstim, leftstim, rightstim, reinforced1, reinforced2,reinforced3, Arew, Brew,Crew,bin, chosen_stim, outcome))
  yz <- melt(data = yz, id.vars = c("trial","subject"), measure.vars = c("p_A", "p_B", "p_C"))
  
  sub_plot <- ggplot(data = yz, aes(x = trial, y = value, color = variable)) + geom_smooth()  + scale_y_continuous(limits = c(0,1))+ ggtitle(paste0(yz$subject, " trials won: ", sum(x$outcome))) + labs(y = "p(choice)")
  
  zzz[[sub]] <- x
  sub_plots[[sub]] <- sub_plot
}

zzz <- do.call(rbind, zzz)

n <- length(list.files())

toplot <- zzz %>% group_by(trial) %>% summarise(n_A = length(which(chosen_stim == "A"))) %>% mutate(p_A = n_A/n)
toplot <- zzz %>% group_by(trial) %>% summarise(n_B = length(which(chosen_stim == "B"))) %>% mutate(p_B = n_B/n) %>% right_join(toplot, by = "trial")
toplot <- zzz %>% group_by(trial) %>% summarise(n_C = length(which(chosen_stim == "C"))) %>% mutate(p_C = n_C/n) %>% right_join(toplot, by = "trial")
  
plot.me <- melt(data = toplot, id.vars = "trial", measure.vars = c("p_A", "p_B", "p_C"))

sample_loess <- ggplot(plot.me, aes(x = trial, y = value, color = variable)) +geom_point()  + geom_smooth() + scale_y_continuous(limits = c(0,1))+ ggtitle("Entire sample behavior")

cowplot::plot_grid(reinforcement_schedule, sample_loess, nrow = 1)

for(sub in 1:length(list.files())){
  sub_plot <- sub_plots[[sub]]
  bla <- cowplot::plot_grid(reinforcement_schedule, sub_plot, nrow = 1)
  plot(bla)
}

dev.off()



# test subject ------------------------------------------------------------

b.chosen <- read.delim('~/Desktop/018_b_chosen.txt')
test.sub <- zzz %>% filter(subject == "018_lq")
test.sub$mat_choose <- c(NA,b.chosen$X2)

yz <- dplyr::select(test.sub, -c(topstim, leftstim, rightstim, reinforced1, reinforced2,reinforced3, Arew, Brew,Crew, chosen_stim, outcome, mat_choose))
yz <- melt(data = yz, id.vars = c("trial","subject"), measure.vars = c("p_A", "p_B", "p_C"))

sub_plot <- ggplot(data = test.sub, aes(x = trial, y = value, color = variable)) + geom_smooth()  + scale_y_continuous(limits = c(0,1))+ ggtitle(paste0(yz$subject, " trials won: ", sum(x$outcome)))

# 
# for()

