
# this is for getting a look at the structure of bandit data bc R > matlab --------
devtools::install_github("matsukik/mrsat")
library(mrsat)

library(tidyverse)
library(rprime)
library(wrapr)

# A function to prepare all eprime data simultaneously
reduce_wm <- function(wm_path) {
  # Read in a text file generated by Eprime
  wm_lines <- read_eprime(wm_path)
  # Convert lines from an Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(wm_frames)
  browser()
  # Select the columns we want for a tibble called "dat".
  dat <- experiment_df %>%
    select(qc(Arew, Brew, Crew,
      topstim, leftstim,rightstim, reinforced1,
      reinforced2, reinforced3, Cycle, Sample, showstim.ACC, showstim.RT, showstim.RESP)) #%>% mutate(id = unique(.$Subject))
  # dat <- experiment_df %>%
  #   select(qc(Arew, Brew, Crew,
  #             topstim, leftstim,rightstim, reinforced1,
  #             reinforced2, reinforced3, showstim.RESP, showstim.ACC)) #%>% mutate(id = unique(.$Subject))
  # 
  # Only put the actual trials in "dat".
  dat <- dat[2:301, ]
}

##slight modifcation of the above

stims_fun <- function(wm_path) {
  # Read in a text file generated by Eprime
  wm_lines <- read_eprime(wm_path)
  # Convert lines from an Eprime file into EprimeFrame objects
  wm_frames <- FrameList(wm_lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(wm_frames)
  browser()
  # Select the columns we want for a tibble called "dat".
  #dat <- experiment_df %>% select(qc(topstim, leftstim,rightstim)) #%>% mutate(id = unique(.$Subject))
  dat <- experiment_df %>%
    select(qc(Arew, Brew, Crew,
              topstim, leftstim,rightstim, reinforced1,
              reinforced2, reinforced3))#, showstim.RESP, showstim.ACC)) #%>% mutate(id = unique(.$Subject))
  # 
  # Only put the actual trials in "dat".
  dat <- dat[2:301, ]
  dat$topstim <- gsub(".bmp", "",dat$topstim, fixed = TRUE)
  dat$leftstim <- gsub(".bmp", "",dat$leftstim, fixed = TRUE)
  dat$rightstim <- gsub(".bmp", "",dat$rightstim, fixed = TRUE)
  dat
}


setwd("~/Desktop/bandit_scripts/Bandit_withrest/")
dirs <- list.dirs("~/Desktop/bandit_scripts/Bandit_withrest")[c(-1, -81)]
for(sub in list.files()){
  # sub <- list.dirs("~/Desktop/bandit_scripts/Bandit_withrest")[2]
  print(sub)
  txt.file <- paste0(sub, "/",list.files(sub)[3])
  txt.path <-paste0(getwd(), "/", txt.file)
  temp <- stims_fun(txt.path)
  rownames(temp) <- 1:300
  
  write.csv(temp, file = paste0(sub, "/stims_",sub,".csv"), row.names = FALSE, quote = FALSE)
}

x <- read.csv("10/stims_10.csv")
y <- read.csv("102/stims_102.csv")

head(x);head(y)
tail(x); tail(y)


# setwd("~/Desktop/bandit_sandbox/")
# library(R.matlab)
# df <- R.matlab::readMat("./for_michael/bandit_stats.mat")
# 
# t2 <- readMat("./for_michael/subjects_data.mat")
# 
# x <- read.table("./for_michael/bandit_data.dat", 
#            header=TRUE)
# 
# print(df$bandit.stats[,1] )
# print(x$id)
